### ISSUE TITLE
可能不兼容ksu？

### ISSUE THREAD

**Issue by lisansas** [Mzdyl/OneUI_CSC_Features#1]
我是S23U,ONE UI5.1.

之前使用magisk delta挂载，使用精简模式，所有功能正常。

但我卸载magisk，改用ksu后，除了录制通话外的所有功能都不正常。

不知道是不兼容ksu还是因为之前magisk版本遗留下来的缓存。

**Comment by Mzdyl** [comment]
ksu 因为 S21 不支持所以没研究
不过应该不难适配，抽空我试试
